name = "RCalibration"
uuid = "0f729a95-7ef5-4eb3-baf3-d58bce7f82ed"
authors = ["David Widmann <david.widmann@it.uu.se>"]
version = "0.1.0"

[deps]
CalibrationErrors = "33913031-fe46-5864-950f-100836f47845"
CalibrationTests = "2818745e-0823-50c7-bc2d-405ac343d48b"

[compat]
CalibrationErrors = "0.6"
CalibrationTests = "0.6"
julia = "1.3"
